### ISSUE TITLE
才看到大佬开源了个博客小程序，我也弄了个hexo版本的小程序

### ISSUE THREAD

**Issue by yicm** [CavinCao/mini-blog#10]
- 可以支持PC端和小程序一次写作，同步发布； 
- 评论支持同步

感兴趣的可以去尝试下： https://github.com/yicm/HMP  

小程序码 

![image](https://user-images.githubusercontent.com/18110379/66618911-9af52d80-ec0d-11e9-85e4-bf87d3578db2.png)

**Comment by MakerGYT** [comment]
分享一种生成博客小程序的思路，在文章来源上，通过webhook与github仓库(可以是hexo或jekyll源码)同步，或者说其实与博客构建方式无关，只关注markdown,化繁为简，回归写博文的初衷。不用简单搬运公众号文章，毕竟小程序流量与存客门槛相比公众号要高很多。

![微信搜索小程序源创智造](https://imgkr.cn-bj.ufileos.com/3cc9ee96-a315-43e0-b9b7-d8a760319ddd.png)
![预览](https://imgkr.cn-bj.ufileos.com/25ec7042-73f7-4c76-8389-d733a609735c.gif)

**Comment by CavinCao** [comment]
Hi，
	感谢关注～
	mini-blog的初衷是脱离所有后端，同步公众号文章只是一种实现方式，完全可以重写syncService云函数来实现任何形式的文章同步，不管你用hexo还是wordpress～
