### ISSUE TITLE
【手动执行adminService报错】Sorry, 很高兴见到你。有一个报错，想请求帮助，我的确不太知道原因

### ISSUE THREAD

**Issue by lanhuaguizha** [CavinCao/mini-blog#3]
你好，上传该云函数完成，手动执行报错。正常配置了把名单和Env, AppSecret, AppI
![Uploading 豆芽图片20190717141748863.png…]()
![Uploading 豆芽图片20190717141934417.png…]()

d

**Comment by lanhuaguizha** [comment]
![豆芽图片20190717141748863](https://user-images.githubusercontent.com/9106780/61352017-deeec580-a89e-11e9-9597-68153f17fc87.png)

**Comment by lanhuaguizha** [comment]
![豆芽图片20190717141934417](https://user-images.githubusercontent.com/9106780/61352047-f037d200-a89e-11e9-8932-09ae8f1f5973.png)

**Comment by CavinCao** [comment]
可参考相关部署问题汇总：https://www.bug2048.com/wechat20190718/
