### ISSUE TITLE
小程序后台管理无法保存文章内容

### ISSUE THREAD

**Issue by wuzhongyi1105** [CavinCao/mini-blog#5]
小程序后台管理无法保存文章内容，标题和题图是可以保存的，然后简介和文章内容都无法保存，提示是保存成功，但是再点回去还是空白。并且云开发的数据库里也没有相关的数据，只有标题，真机调试后发现 article.js 的42行报错，请问如何debug，在错误信息中没有找到相关信息。

**Comment by ldyivan** [comment]
我这边连管理员后台的入口不显示，授权的是小程序管理员微信也没显示

**Comment by wuzhongyi1105** [comment]
@ldyivan 你云函数的变量有没有设置？

> [后台管理是通过配置openId来实现权限管控的，具体是在adminService云函数下配置对应的环境变量，key名为author,value为相应的openId,可以配置多个，逗号分隔即可。](https://mp.weixin.qq.com/s/GLNSHdWIowwdb5_GHPJkmg)

**Comment by CavinCao** [comment]
真机调试后发现 article.js 的42行报错
该问题已经修复～
