### ISSUE TITLE
发现几个小问题

### ISSUE THREAD

**Issue by jzsjiale** [CavinCao/mini-blog#8]
首先程序做的挺不错的，发现几个小问题，可以调试下看是不是有相关问题的存在：
1、列表页的图片都无法显示，云平台cloud://协议的图片是不是不能放在background-image里，应该用image组件吧。
2、模板中很多循环的地方没有加wx:key。
3、真机测试很多时候程序打开后都是白屏，只显示灰色背景，没有加载任何内容。首页、专题、我的，都是这样。
4、发布文章时富文本编辑器无法插入图片，不知道后续会不会增加这部分功能。

**Comment by CavinCao** [comment]
1.是的，给小程序那边提了，不懂会不会采纳，支持background-image，目前图片还是切到七牛云上了，CDN流量伤不起
2. 这个可以加下，影响不大
3. 得提供实际错误，理论上正确部署不会有这样的情况
4. 发布文章时富文本编辑器是腾讯自带的，可以参考下官方文档

**Comment by jzsjiale** [comment]
3、开发环境下可以显示，就是加载很慢，真机调试默认可以显示，预览模式，和上传后的体验版本无法正常显示。
4、富文本编辑器是腾讯带的，但是上传图片的方法是需要小程序本身来实现的，insertImage()，可以考虑增加一下。

**Comment by CavinCao** [comment]
3.有对应的日志或者复现场景吗
4.了解了，起初是想实验下小程序的富文本组件的，文章的新增编辑不会放在小程序端实现的，太不方便了，本身是个伪需求

**Comment by jzsjiale** [comment]
3、刚看了下预览模式下，vconsole下的报错是这个，还没具体看程序：
`thirdScriptError TypeError: require(...) is not a function TypeError: require(...) is not a function at require (towxml/main.js:28:14) at (app.js:34:11) at require (WASubContext.js:1:44444) at at (app-service.js:9280:10)`
4、其实思路很好，完全不依赖服务器、域名，有很多个人用户可以直接无成本使用，要是发文章能做成区块化编辑器就好了，比富文本好，很多小程序有这种功能。

**Comment by CavinCao** [comment]
3、这个提示应该挺清楚了，可以具体定位下，目前我这边复现不了
4、还是觉得小程序端新增文章是伪需求。倒是可以通过云开发的HTTP API自己写个管理端,比如通过electron+vue写个桌面应用，用来管理、编写文章
