### ISSUE TITLE
关于文章管理我这里有个思路

### ISSUE THREAD

**Issue by wellmoonloft** [CavinCao/mini-blog#9]
自从halo群里面有人分享您的项目，我这边就一直在关注。
关于文章管理这边我似乎有个思路，直接将文章Typora之类的编辑器写好，然后转成html的方式，复制进数据库里面。
然后小程序用html2wxml的插件呈现出来就可以了。
至于图片等等素材，可以直接用七牛云存储来解决，个人免费10个G，[我之前写过一个文章](https://www.jianshu.com/p/6e045606d879)关于Typora+七牛云+自动上传图片的工具，全都配置好之后使用起来非常简单。
这样做的唯一弊端就是需要单独注册一个域名，而且换电脑的话更新文章比较麻烦，但好处是不需要再维护个微信公众号了，也不需要去穷举IP。

**Comment by CavinCao** [comment]
感谢关注～

公众号只是其中一种手段，之前的文章有提到过，只要重写syncService这个云函数就可以了，不管你的文章来自哪里

另外你也可以通过云开发提供的HTTP API来实现，比如通过pyhthon写个脚本将本地的文章同步到云数据库中（只要满足mini_posts的结构即可）
